export const GUN_TYPES = {
  handgun: {
    name: "Handgun",
    displayW: 45,
    displayH: 28,
    offsetX: 30,
    offsetY: 42,
    bulletSpeed: 800,
    fireRate: 300,
    bulletDamage: 25,
    muzzleOffset: 28,
  },
  shotgun: {
    name: "Shotgun",
    displayW: 90,
    displayH: 32,
    offsetX: 10,
    offsetY: 40,
    bulletSpeed: 600,
    fireRate: 800,
    bulletDamage: 60,
    muzzleOffset: 50,
  },
  machineGun: {
    name: "Machine Gun",
    displayW: 60,
    displayH: 20,
    offsetX: 10,
    offsetY: 40,
    bulletSpeed: 1000,
    fireRate: 100,
    bulletDamage: 15,
    muzzleOffset: 52,
  },
};
